include:
  - project: templates/gitlab/container-ci
    ref: main
    file: container-ci-kaniko.yml

.container-building-variables:
  variables: &container-building-variables
    CONTAINER_IMAGE_NAME: ${CI_PROJECT_NAME}
    CONTAINER_IMAGE_PACKAGE: ${CONTAINER_IMAGE_NAME}-${CONTAINER_IMAGE_TAG}.tar
    ALPINE_VERSION: "3.18.0"
    CONTAINER_IMAGE_TAG: "3.18"
    ARCHITECTURE: "aarch64"
    CONTAINER_BUILD_ARGS: "--build-arg alpine_version=${ALPINE_VERSION} --build-arg tag=${CONTAINER_IMAGE_TAG} --build-arg git_hash=${CI_COMMIT_SHORT_SHA} --build-arg architecture=${ARCHITECTURE}"
    MINIROOTFS_URL: http://dl-cdn.alpinelinux.org/alpine/v${CONTAINER_IMAGE_TAG}/releases/${ARCHITECTURE}/
    MINIROOTFS_TGZ: alpine-minirootfs-${ALPINE_VERSION}-${ARCHITECTURE}.tar.gz

# BUILD

build-alpine-3.18:
  extends: .container-build
  variables:
    <<: *container-building-variables
  before_script:
    - wget -O docker/assets/${MINIROOTFS_TGZ} ${MINIROOTFS_URL}${MINIROOTFS_TGZ}

# PUBLISH

publish-alpine-3.18:
  extends: .container-publish
  variables:
    <<: *container-building-variables
    CONTAINER_REGISTRY_IMAGE_TAG: ${ALPINE_VERSION}
    ADDITIONAL_DESTINATIONS: "${CONTAINER_IMAGE_TAG} latest"
  before_script:
    - wget -O docker/assets/${MINIROOTFS_TGZ} ${MINIROOTFS_URL}${MINIROOTFS_TGZ}
