echo -e "--------------------------------------------------------------------------------"
echo -e "-- ONESPAN OFFICIAL IMAGE.                                                    --"
echo -e "--                                                 alpine:           $BUILD_HASH --"
echo -e "--                                                                 $BUILD_DATE --"
echo -e "-- Use with caution.                                                          --"
echo -e "--------------------------------------------------------------------------------"
